# Generated by Django 4.0.6 on 2022-07-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('feature', models.CharField(max_length=100, verbose_name='Feature')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('icon', models.CharField(choices=[('lni-cog', 'Gear'), ('lni-layers', 'Design'), ('lni-leaf', 'Leaf'), ('lni-laptop-phone', 'Device'), ('lni-rocket', 'Rocket')], max_length=20, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
