# Generated by Django 4.0.6 on 2022-07-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='side',
            field=models.CharField(default='left', max_length=5, verbose_name='Side'),
        ),
    ]
